name: Build and Deploy to S3

on:
  push:
    branches:
      - main  # Cambia a tu rama principal, si es diferente

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout Code
        uses: actions/checkout@v3

      # Paso 2: Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # O la versión que uses

      # Paso 3: Instalar dependencias
      - name: Install Dependencies
        run: npm ci

      # Paso 4: Construir la aplicación
      - name: Build React App
        run: npm run build

      # Paso 5: Subir a S3
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}  # Nombre del bucket S3
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Clave de acceso
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Clave secreta
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}  # Token de sesión temporal
          AWS_REGION: us-east-1
          SOURCE_DIR: dist  # La carpeta dist contiene los archivos generados
