name: Build and Deploy to S3

on:
  push:
    branches:
      - main  # Cambia a tu rama principal, si es diferente

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # O la versión que uses

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Upload to S3
        run: |
          aws s3 sync ./dist/apps/catalog s3://pruebitaaverqonda
        env:
          AWS_S3_BUCKET: pruebitaaverqonda  
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Clave de acceso
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Clave secreta
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}  # Token de sesión temporal
          AWS_REGION: us-east-1
          SOURCE_DIR: dist  
          
  sonarcloud:
    name: SonarQube Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  
      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  send-email:
    runs-on: ubuntu-latest
    needs: build-and-deploy  # Asegura que este paso se ejecute después del despliegue en S3
    if: always()  # Asegura que este paso se ejecute independientemente de si el paso anterior fue exitoso o no

    steps:
      - name: Invoke Lambda function to send email on success
        if: success()  # Este paso solo se ejecuta si el paso anterior fue exitoso
        run: |
          aws lambda invoke \
            --function-name EmailFunction \  # Nombre de tu función Lambda
            --payload '{"status": "Success", "message": "The deployment to S3 was successful."}' \
            response.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1  # Ajusta la región si es necesario

      - name: Invoke Lambda function to send email on failure
        if: failure()  # Este paso solo se ejecuta si el paso anterior falló
        run: |
          aws lambda invoke \
            --function-name EmailFunction \  # Nombre de tu función Lambda
            --payload '{"status": "Failure", "message": "The deployment to S3 failed."}' \
            response.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1  # Ajusta la región si es necesario

      - name: Print Lambda response
        run: cat response.json
